### ISSUE TITLE
当我用FastJson的时候，图显示的调用层级很浅

### ISSUE THREAD

**Issue by thirteenthree** [Vanco/SequencePlugin#106]
![AppTest_test8](https://user-images.githubusercontent.com/35475497/139643158-1ea81694-d26b-4cfb-b19a-d58e09277bb5.png)
![image](https://user-images.githubusercontent.com/35475497/139643233-83da27d7-b726-4e9b-a406-b2f22f3ad843.png)

**Comment by Vanco** [comment]
The plug-in does not go deep into external classes, but only focuses on the code in this project.
