### ISSUE TITLE
Support for Rider / PhpStorm and others JetBrains IDE

### ISSUE THREAD

**Issue by ennerperez** [Vanco/SequencePlugin#108]
Very useful plugin, but can only be used in IntelliJ, so, could be great to prepare it for work in all JerBrains IDEs
- [ ] Web Storm
- [ ] PHP Storm
- [ ] Rider
- [ ] GoLand
- [ ] CLion

**Comment by Vanco** [comment]
This plugin is for JAVA and KOTLIN (partial) language ONLY.   

There is no plan for other languages.
