### ISSUE TITLE
Exclude selected class from diagram

### ISSUE THREAD

**Issue by kolisko** [Vanco/SequencePlugin#109]
Add context menu item to remove class from diagram and add to 'Exclude from diagram' Preferences

**Comment by Vanco** [comment]
These functions already exist.

1) Right click class shape, will show `Remove class CLASSNAME` menu.
2) Open idea preferences by Settings > Tools > Sequence Diagram

**Comment by mikeliucc** [comment]
How to restore the classes that are removed?

**Comment by Vanco** [comment]
You can select the same method generate from start, it will open a new
tap. Each tab have its own filter. The remoe class action, actually add a
class filter to it.

We will think and remove filter function in future versions.

Thank you for your feedback.

automike ***@***.***> 于 2023年3月31日周五 上午3:17写道：
