### ISSUE TITLE
Cannot load any projects if I have this plugin installed

### ISSUE THREAD

**Issue by klenium** [Vanco/SequencePlugin#11]
I've just installed the plugin, but after restarted my Intellij IDEA (2016.2.5), I got this error:
![plugin_error](https://cloud.githubusercontent.com/assets/4959489/20652422/262152c0-b4f9-11e6-8e54-b2418a8910ce.png)
Unless I uninstall the plugin, I cannot open any other projects too.

**Comment by Vanco** [comment]
I could not reproduce the error on my 2016.2.5 for Windows.   Could you provide more error information.

**Comment by klenium** [comment]
How should I help more? I mean there's nothing else I see.

**Comment by Vanco** [comment]
I see. It the first time hear the SequenceDiagram block load project. But I don't have any solution based on your information.  For you, you can try the plugin with new IDEA 2016.3 or try from another computer of college, whether the they have same issue.   Send me the IDEA.log file.  And Thanks for you interesting the plugin.

**Comment by klenium** [comment]
Strange, I've just updated my IDEA, and with the new version it works fine.
