### ISSUE TITLE
Include non project class to diagrams

### ISSUE THREAD

**Issue by kolisko** [Vanco/SequencePlugin#110]
Now is possible to setup to show

- All classes
- Only project classes

on diagram and select specific classes to `Exclude from diagram` in Preferences.

Could you add also the opposite settings `Include to diagram` to Preferences? It means to add specific non project classes to diagrams when the `Display only project classes` is checked.

**Comment by Vanco** [comment]
The generate setting is replace in Sequence Diagram tool windows.
![tool-windows-settings](https://user-images.githubusercontent.com/11991700/140671850-c5925444-ff32-4381-84b1-fa7c4d124583.png)

Try to use  `Sequence Diagram Options` combination with `Exclude from diagram` to achieve your purpose .

**Comment by Vanco** [comment]
Please try `Exclude from diagram` combine with `preffered method` list for this.
