### ISSUE TITLE
V2.1.3 does not jump to the code

### ISSUE THREAD

**Issue by diguage** [Vanco/SequencePlugin#113]
Sequence Plugin: 2.1.3

IntelliJ IDEA:

```
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021

Subscription is active until May 6, 2022.
Runtime version: 11.0.12+7-b1504.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2560M
Cores: 12
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: cn.haojiyou.CodeGlance3 (2.1.1-2021.1.3), GrepConsole (12.0.211.6086.4), String Manipulation (8.22.203.000.1), com.intellij.selenium (212.5457.18), com.wakatime.intellij.plugin (13.1.3), Key Promoter X (2021.3), org.asciidoctor.intellij.asciidoc (0.35.12), lermitage.intellij.extra.icons (1.66.0.203), PlantUML integration (5.7.2), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7), izhangzhihao.rainbow.brackets (6.21), SequenceDiagram (2.1.3), MavenRunHelper (4.18.212.000.3), com.haulmont.jpab (5.7-212), com.intellij.javaee.ejb (212.5080.8), cn.wuzhizhan.plugin.mybatis (2020.12.18), com.alibaba.p3c.smartfox (2.1.1)
Kotlin: 212-1.5.31-release-546-IJ4638.7
```

**Click the method of the sequence diagram, the editor does not jump to the code.**

**Comment by Vanco** [comment]
Some Kotlin code jump is not implemented yet.    Some more work need to do.   Pure java code will be fine.   Is your code mixed with Kotlin?

**Comment by diguage** [comment]
> Some Kotlin code jump is not implemented yet. Some more work need to do. Pure java code will be fine. Is your code mixed with Kotlin?

My project is a pure java project. No line of Koltin code.

The previous version is good.

**Comment by diguage** [comment]
There is another bug: **can not delete method invoke.**

**Comment by diguage** [comment]
There is another bug: **can not delete method invoke.**

The previous version is good.

**Comment by josways** [comment]
I also have this problem，
But sometimes it will succeed
( pure java project )

`
IntelliJ IDEA 2021.2.3 (Community Edition)
Build #IC-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Non-Bundled Plugins: SequenceDiagram (2.1.3)
`
