### ISSUE TITLE
Can you raise this label “Remove Class XXXXX” to the top？

### ISSUE THREAD

**Issue by ZhangDi-d** [Vanco/SequencePlugin#116]
Imagine I have a method like the following:

```java
    @PostMapping("/test")
    public String testList() {
        List<String> list = new ArrayList<>();
        list.add("1");
        return "success";
    }
```

When I create a sequence diagram, it will look like this ： 
![image](https://user-images.githubusercontent.com/29948535/147739071-fb84c17a-08cf-45fc-88c5-d9c6600330d1.png)

If i click the “List” with right button ，the lable “Remove class List” can not be saw ：
![image](https://user-images.githubusercontent.com/29948535/147739233-e057b4d3-bd5d-48bc-8723-33fa2bfe7d79.png)

So can you please put this label "Remove Class XXXXX" near the top of the label "GO to Source" for easy operation.

**Comment by Vanco** [comment]
Yes I can.
