### ISSUE TITLE
Mermaid format export not possible from the UI

### ISSUE THREAD

**Issue by lw-mcno** [Vanco/SequencePlugin#120]
Thanks for the useful plug-in. I'm unable to export Mermaid files, event though the README explicitly mentions this functionality.

I've checked and the generating code seems to support exporting Mermaid-formatted files (for file names ending with `.mmd`), but it doesn't seem possible to access it from the UI.

At the moment, there are only buttons for exporting PNGs and PlantUML files. File extension gets added automatically and doesn't seen possible to override.

BTW. Is it / would it be possible to include parameter names and types on calls and return value types on method returns?

**Comment by Vanco** [comment]
When export, choose File format, type file name (no need type file extension):
- PlantUML(.puml) File
- Mermaid(.mmd) File

Both file are text file, you can open with text editor to review it.
![export](https://user-images.githubusercontent.com/11991700/163709310-053aaf5c-4de9-461f-bdbf-02f1de8ae38d.png)

> BTW. Is it / would it be possible to include parameter names and types on calls and return value types on method returns?

You can uncheck `Show simple call name` option in Sequence Diagram settings.
