### ISSUE TITLE
Hope to increase the exclusion of jdk method calls

### ISSUE THREAD

**Issue by fage520** [Vanco/SequencePlugin#121]
The text is based on google translate, please understand

When only the project class is displayed, the jdk method will be in the generated diagram. I am not interested in the implementation of jdk, can I block it?

This is my first time submitting an issue, please let me know if there are any shortcomings, thank you

**Comment by fage520** [comment]
It is recommended to add exclude settings based on package paths, for example to exclude jdk:
"java.*"

**Comment by Vanco** [comment]
- Exclude classes from diagram by Settings > Tools > Sequence Diagram

You can set there.

**Comment by fage520** [comment]
Thanks, it was my mistake, I didn't notice
