### ISSUE TITLE
Unable to export images

### ISSUE THREAD

**Issue by zixuan2020** [Vanco/SequencePlugin#122]
When I am exporting images, the following exception occurs
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/20490066/163818110-3dfca819-acf8-451c-8a13-23f24d71a7e0.png">
<img width="262" alt="image" src="https://user-images.githubusercontent.com/20490066/163818156-9bbc6d5b-c147-4b8a-8584-1e8354eebd8b.png">

**Comment by Vanco** [comment]
Could please send me idea.log file?   It will help to find the issue.

**Comment by Vanco** [comment]
It's the limit of Raster, width * height must less than Int.MAX_VALUE.  so large image will throw `NegativeArraySizeException`.

Solution: Change the export format to SVG.  (In v 2.1.8)
