### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by jorabin** [Vanco/SequencePlugin#124]
Really like this project, absolutely great!

Trying to build on macOS Intel etc. getting the following, would be grateful for any ideas.

A problem occurred configuring root project 'SequencePlugin'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.4.0.
     Required by:
         project : > org.jetbrains.intellij:org.jetbrains.intellij.gradle.plugin:1.4.0
      > No matching variant of org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.4.0 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.4' but:
          - Variant 'apiElements' capability org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.4.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'runtimeElements' capability org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.4.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')

**Comment by Vanco** [comment]
Did you gradle sync successfully?   you need internet to retrieve "org.jetbrains.intellij" gradle plugin 1.4.0.

**Comment by Vanco** [comment]
Try to verify the following works:
``` 
    maven { url = uri("https://maven.aliyun.com/repository/public") }
    maven { url = uri("https://www.jetbrains.com/intellij-repository/releases") }
    maven { url = uri("https://cache-redirector.jetbrains.com/intellij-dependencies") }
```

**Comment by jorabin** [comment]
thanks for your very very swift response! Bear with me as I am a maven person and know little gradle.  

Builds fine with java 11 configured, previous was with java 8.
