### ISSUE TITLE
IDEA意图意外的自动触发

### ISSUE THREAD

**Issue by taoyyz** [Vanco/SequencePlugin#127]
* 当我使用Windows平台的IDEA 2022.1和IDEA 2022.2 EAP时，此插件提供的意图：**"Generate sequence diagram"会自动触发，当我的鼠标或光标停留在"Generate sequence diagram"这个意图项上时**。
* 它造成的后果是Sequence Diagram窗口会意外的开启，并且每当我把鼠标或光标移动到"Generate sequence diagram"这个意图项时，都会触发一次开启Sequence Diagram窗口。
* 正常情况下，我期望的触发条件是当我对"Generate sequence diagram"意图项按Enter或点击，然后触发。然而现在是鼠标或光标放置在"Generate sequence diagram"上就会触发这个问题。
这个问题的**发生条件在：我开启了IDEA的意图功能的Ctrl+Q预览。**
![image](https://user-images.githubusercontent.com/79864620/173997308-1c9f9a99-36f0-477d-bc36-ed1000cdfb9f.png)

我尝试给IntelliJ IDEA support发送了邮件，得到的回答是：
>这个功能是插件里，使用这个 API 控制的： https://github.com/JetBrains/intellij-community/blob/b0734614748dab623c69f0cae3d74a939862ccef/platform/analysis-api/src/com/intellij/codeInsight/intention/IntentionAction.java#L139
这个是 SequenceDiagram 插件的问题，你需要汇报给这个插件厂商，来修复：https://github.com/Vanco/SequencePlugin
Best Regards
Lejia Chen
JetBrains Support

希望能尽快修复这个问题，谢谢！

**Comment by Vanco** [comment]
fixed in v2.1.10
