### ISSUE TITLE
[BUG] Un-support Utf-8 Chinese words.

### ISSUE THREAD

**Issue by TinyZzh** [Vanco/SequencePlugin#128]
![image](https://user-images.githubusercontent.com/5763397/178227321-d772955c-fb5f-4503-a585-659511301031.png)

**Comment by TinyZzh** [comment]
@Vanco

**Comment by Vanco** [comment]
> ![image](https://user-images.githubusercontent.com/5763397/178227321-d772955c-fb5f-4503-a585-659511301031.png)

The image show nothing related to SequenceDiagram plugin.   Please give more specific discription on the issue.

**Comment by TinyZzh** [comment]
i make a mistake, sorry about that!

**Comment by Vanco** [comment]
First all, The SequenceDiagram plug can only generate sequence diagram from JAVA / Kotlin source code.   It can export sequence diagram as Mermaid(.md) file.   But is CAN NOT read Mermaid(.md) file.   The issue you mentiond is not releated to SequenceDiagram plugin.  Maybe you should look at the Mermaid plugin or something.
