### ISSUE TITLE
export to svg error

### ISSUE THREAD

**Issue by LuBangTao** [Vanco/SequencePlugin#129]
when I exported to svg, I got:
![image](https://user-images.githubusercontent.com/22848900/178425024-af574829-4a67-4001-9677-cad8d6f1b202.png)

and it can't open with Adobe Illustrator...
![image](https://user-images.githubusercontent.com/22848900/178425278-02a961e5-b4cd-4004-aa65-3c04545ccdb4.png)

“此SVG无效，请在打开之前进行验证”

**Comment by Vanco** [comment]
Could you please attach the SVG file?

**Comment by LuBangTao** [comment]
![TaskBlh_saveTask](https://user-images.githubusercontent.com/22848900/179905837-94b32e11-14cf-45ab-9327-fe56a1fcaed2.svg)

Thanks

**Comment by Vanco** [comment]
The root cause found.   It is the `λ→` not show correct in SVG file.   The fix will be availabe in next release.

Quick fix:   opt-out `Show lambda call` in Settings > Tools > Sequence Diagram
