### ISSUE TITLE
Exclusion wild cards not working

### ISSUE THREAD

**Issue by jayeshgarg** [Vanco/SequencePlugin#13]
I am trying to exclude some files while trying to create the SD, but it is still including those files.

Eg. My wildcard entry is :
**Builder
**.*Builder
*Builder

But still those files are included in the diagram. Please let me know in case I made an incorrect entry.

PS. I am trying to exclude all the classes whose name ends with Builder

**Comment by Vanco** [comment]
current only support exclude "some.package.name.*" or "other.package.name.**" or "an.package.ClassName" format.  but do not support the format as your setting.  Which may support in latter version update.  
For instead, You can generate the SD first, than select the Builder you want to remove, and remove it from context menu.

**Comment by jayeshgarg** [comment]
Thank you for your reply. I have one last query, what is the difference between "some.package.name.*" and "other.package.name.**". What different that extra * makes here? Does it mean to include sub packages as well?

**Comment by Vanco** [comment]
yes，it is mean include sub packages.
