### ISSUE TITLE
Export diagram Options

### ISSUE THREAD

**Issue by danielferreiracastro** [Vanco/SequencePlugin#133]
When I click on Export Image I am only allowed to choose svg format.  It would be interesting if:

- We could choose the image format to export to;
- If we could choose to not generate image with transparent background.  This would simplify when we try to produce a diagram and insrt in a page, confluence for example, where I can not configure the background of that page.

**Comment by Vanco** [comment]
Since v2.2.0, the background already transparent.

**Comment by danielferreiracastro** [comment]
I see.  The requisition is to make optional the background transparent so I can choose if I want it or not.

**Comment by danielferreiracastro** [comment]
Will have a new release with the changes you just made?

**Comment by Vanco** [comment]
Will be included in the next (v2.2.1) release at the end of August.
