### ISSUE TITLE
generate sequenceDiagram Failed

### ISSUE THREAD

**Issue by za34792635** [Vanco/SequencePlugin#134]
![image](https://user-images.githubusercontent.com/16346687/182750104-4106f97d-75c0-4f4e-9435-c28356aa71db.png)

I want  to generate a  Diagram for SqlSessionFactoryBuilder.build()  in Junit   , but it look like doesn't work

**Comment by za34792635** [comment]
whatever I saved my setting and click the "Run" button , it doesn't show any more diagram

**Comment by Vanco** [comment]
> 
> I want to generate a Diagram for SqlSessionFactoryBuilder.build() in Junit , but it look like doesn't work

You should navi to source of SqlSessionFactoryBuilder.build(), than generate. for your porpse.

If you don't have source. the generate will not work. 

Mostly, it generate on your project source and external call from your source.  external call external will not follows.

**Comment by Vanco** [comment]
![build](https://user-images.githubusercontent.com/11991700/223889030-9c843958-2a30-4e4f-a3ea-ec80a9ec5a38.png)

A trick:   
1. double click the build method block(not the method call name)(see blue in diagram), will navigate to the source file. 
2. generate diagram there.
