### ISSUE TITLE
How to use smart interface in v.2.2.5 for JAVA IJ2021.2 

### ISSUE THREAD

**Issue by zyeewang** [Vanco/SequencePlugin#144]
Language: JAVA

IDEA: 2021.2

SequenceDiagram: v2.2.5

As question described, I want know how I can use smart interface in SequenceDiagram,  it seems doesn't work for me. And I'm pretty sure that the target "interface" only have one implementation class.
![image](https://user-images.githubusercontent.com/77087540/201325928-bf9b2de7-4f5e-4c4f-80c9-902312995a77.png)

![image](https://user-images.githubusercontent.com/77087540/201326006-693eeda7-84bc-4c13-8a39-f0d6e3c07684.png)

**Comment by Vanco** [comment]
please try version 2.2.6.

**Comment by zyeewang** [comment]
> please try version 2.2.6.

v2.2.6 neither doesn't work, but v2.2.3 function normally.
