### ISSUE TITLE
The lambda block cannot be deleted

### ISSUE THREAD

**Issue by alvin-susu** [Vanco/SequencePlugin#145]
**Describe the bug**
The lambda block cannot be deleted, and the detailed content of the lambda expression cannot be displayed. This style gives people a bad experience

**Plugin & IDE info:**
 - Plugin Version:2.2.6
 - IntelliJ IDEA 2022.2.3
 - Java

**Additional context**
like this, when you put them in your code, this plugin will show you : () ->，and this can't be removed
![image](https://user-images.githubusercontent.com/61646212/202437779-815f51c8-2879-4eb4-9a2d-27fec54ece54.png)
```java
List<List<Long>> mglist = Lists.newArrayList();
Stream.iterate(0, n -> n + 1).limit(limit).forEach(i -> {
                    mglist.add(request.getPkids().stream().skip(i * 1000).limit(1000).collect(Collectors.toList()));
                });
```
please fix this problem

**Comment by Vanco** [comment]
Try to opt-out `show lambda call` in settings.

**Comment by duomn10** [comment]
@Vanco 
I also encountered this problem, and I fixed it based on the v2.2.6 tag. But I don't know how to submit PR based on tag.

**Comment by Vanco** [comment]
@duomn10 
I create b_v2.2.6 branch for you. Now do what you need to do.  Thanks for your help.

**Comment by duomn10** [comment]
I submitted a PR. Logically, SingleMethodFilter can be allowed according to offset, but I did not add TestCase, all changes should not affect the previous logic as much as possible.
#152
