### ISSUE TITLE
Cannot filter package 'com.base.package.toexclude.**'

### ISSUE THREAD

**Issue by blimaupgrade** [Vanco/SequencePlugin#147]
**Describe the bug**
When adding package filter 'com.base.package.toexclude.**', classes from configured package are still being shown in generated diagram.

**To Reproduce**
1. Go to 'Settings / Tools / Sequence Diagram'
2. Click on 'Add' button from section "exclude from diagram"
3. Scroll down to 'add com.base.package.toexclude.**'
4. Implement class inside package com.base.package.toexclude, using lombok @Builder and apply MyClass.builder().build();
5. Both classes will be shown in diagram (MyClass and MyClass.MyClassBuilder)

**Expected behavior**
Classes from excluded package should not appear.

**Plugin & IDE info:**
 - Plugin Version 2.2.6
 - IntelliJ IDEA 2022.1.4 (Ultimate Edition)
 - Java 11

**Comment by Vanco** [comment]
fixed since v3.x
