### ISSUE TITLE
Support for IntelliJ IDEA 2023 ?

### ISSUE THREAD

**Issue by juergenzimmermann** [Vanco/SequencePlugin#148]
@Vanco Can you give a coarse extimation when a release for IntelliJ 2023 will be available, please? So far there is the 2nd EAP release of IJ 2023.

**Comment by xiexifeng** [comment]
![image](https://user-images.githubusercontent.com/20811876/217182916-41ff1913-6464-45c8-8f51-21392d2d6949.png)
Smart Interface very important。

**Comment by andrebiegel** [comment]
I would like to use it in 2022.3.2 , is there any plan when this plugin will be available ? i tested the alpha version but after installing the plugin intellij doesn´t start any more..

**Comment by Vanco** [comment]
> I would like to use it in 2022.3.2 , is there any plan when this plugin will be available ? i tested the alpha version but after installing the plugin intellij doesn´t start any more..

Should work!

**Comment by juergenzimmermann** [comment]
@Vanco Thank you very much! 3.0.1 works in my projects without any issues.

**Comment by andrebiegel** [comment]
> > I would like to use it in 2022.3.2 , is there any plan when this plugin will be available ? i tested the alpha version but after installing the plugin intellij doesn´t start any more..
> 
> Should work!

in version 3.0.1 it does

**Comment by Vanco** [comment]
latest version is 3.0.4, a little more improve.

**Comment by Vanco** [comment]
> ![image](https://user-images.githubusercontent.com/20811876/217182916-41ff1913-6464-45c8-8f51-21392d2d6949.png) Smart Interface very important。

version 3.0.4 has smart interface in settings.
