### ISSUE TITLE
[Feature Request] Just like blacklist, can a whitelist be implemented

### ISSUE THREAD

**Issue by jayeshgarg** [Vanco/SequencePlugin#15]
Just like blacklist, can a whitelist be implemented.

So that it includes only those classes that are a part of the defined criteria(same way as in blacklist). It may or may not supersede the blacklist present.

eg. If I mention com.abc.**, only classes belonging to this package or any of its sob package will be included rest will be excluded.

**Comment by Vanco** [comment]
add to feature list. Thx

**Comment by jayeshgarg** [comment]
How can I do that?

**Comment by Vanco** [comment]
I have done that. Mean the feature will be available in the future release.  You just need wait.
