### ISSUE TITLE
 `Display only project classes` cannot work correctly

### ISSUE THREAD

**Issue by archzi** [Vanco/SequencePlugin#153]
**Describe the bug**
 `Display only project classes` cannot work correctly
the snapshot is a contrast between version v2.2.6 and v3.0.1

**Expected behavior**

**Screenshots**
diagram v2.2.6 generated
![img](https://user-images.githubusercontent.com/19209941/223913518-c861150b-859d-4853-a49f-c9736a344829.png)
![img_1](https://user-images.githubusercontent.com/19209941/223913532-1be5886d-d5d6-4372-a2f6-71f4faf56612.png)
diagram v3.0.1 generated
![img_2](https://user-images.githubusercontent.com/19209941/223913547-d5f448d9-3283-470f-bc5f-98c9e2201f4f.png)
![img_3](https://user-images.githubusercontent.com/19209941/223913551-b35c86b2-ed67-4a3d-be02-243c111e9ed0.png)

**Plugin & IDE info:**
 - Plugin Version [e.g. 2.2.0]
 - IDE Name & Version [e.g. IDEA Comunity 2022.2]
 - Which language (e.g: Java, Kotlin, Scala, Groovy) you try to generate?

**Additional context**
- code fragment
```java
public static void startService(){

        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.submit(new Runnable() {
            @SneakyThrows
            @Override
            public void run() {
                System.out.println("executor service start!!!");
                Thread.sleep(1000*10);
                System.out.println("Thread done!");
            }
        });
        System.out.println("start done!");
        executorService.shutdown();
    }

```

**Comment by Vanco** [comment]
fixed #153 at v3.0.2
