### ISSUE TITLE
Plant UML Export is broken because of invalid syntax

### ISSUE THREAD

**Issue by TobseF** [Vanco/SequencePlugin#160]
The exported PlantUML sequence diagram cannot be rendered, because of broken syntax:

### Steps to Reproduce
1. Run Sequence Diagram out of a Kotlin function (a Unit test)
2. Export the sequence diagram as PlantUML diagram
3. Open the PlantUML diagram in the IntelliJ PlantUML plugin
4. See, that the PlantUML file cannot be compiled because of a wrong syntax

### Expected behavior
The exported file schould be valid

### Screenshots
> ⚠ Exception
> "After create command you have to send a message to ..."

<img width="472" alt="2023-05-05_11h03_40" src="https://user-images.githubusercontent.com/1190109/236418405-ca05a297-243d-46cf-acd5-c38f342f0e1a.png">

### Plugin & IDE info
 - Plugin Version 3.0.4
 - IDEA Ultimate 2023.1.1.
 - Kotlin File

**Comment by TobseF** [comment]
As a workaround, the problem can be fixed by check "_Skip constructors_".
<img width="286" alt="2023-05-05_11h24_19" src="https://user-images.githubusercontent.com/1190109/236422353-f9f1f080-510d-4f9b-96c3-7564de8f5d28.png">

**Comment by Vanco** [comment]
From official example:
```
@startuml
Bob -> Alice : hello

create Other
Alice -> Other : new

create control String
Alice -> String
note right : You can also put notes!

Alice --> Bob : ok

@enduml
```
the `create` should be `A` create `B`,  same as `Alice -> Other : new` in above example.   But in your code, `CredentialHolder -> CredentialHolder : new` is something wrong?   Please paste your kotlin function source code, it will help me to find the bugs.
