### ISSUE TITLE
Limited to 5 call deep for free version

### ISSUE THREAD

**Issue by Simon-0128** [Vanco/SequencePlugin#161]
I download this plugin from the IDEA marketplace for free, but I recived this msg while using. I noticed that the jetbrains website offer 30-Day Trial, Monthly Subscription and Yearly Subscription to choose, which one should I choose to get the full version? Thx! :)

**Comment by Vanco** [comment]
Either of 30-Day Trial, Monthly Subscription and Yearly Subscription will get full version in different license period:

- 30-Day trial: free use in 30 days with evaluation license
- Monthly Subscription: one month full license
- Yearly Subscription: one year period full license
