### ISSUE TITLE
Issue with full functionality for 30-day trial

### ISSUE THREAD

**Issue by randy** [Vanco/SequencePlugin#163]
Sorry, not filling in the long form for this... It's not a typical bug.

The "5 call deep" limit seems to prevent anything other than the initial call to the method from being mapped, so I went through and tried to "start the trial." Nothing seems to make that take effect. I even tried remove the plugin and letting the marketplace install it from the pricing page.

After that, I still get the "5 call deep" message every time I run the plugin and it still only lists "Actor" and the class I initiated the process from, with only the selected method shown (as shown below), even though there are plenty of other interactions with other classes from that method.

I've verified that I'm getting the v3.0.5 of the plugin, which is stated to be the freemium version, however IJ is still showing "no license." And I'm using IntelliJ 2022.3.3, so this doesn't seem to be a compatibility issue, but rather that the plugin isn't recognizing the 30-day trial.

![image](https://github.com/Vanco/SequencePlugin/assets/22246488/8ed7babb-8343-4428-ba9d-f83ee0071350)

**Comment by Vanco** [comment]
According to your description, there are several possibilities:
1. If you generate from Groovy code, most of time you will get one initially call. It is the limit of Groovy(No UAST support in method body).
2. If you "start the trial" and the trial period expired. You will get "5 call deep" message.
3. If all calls inside `prepareEmail`  are filter out, please try opt-out all checkbox in settings, and remove all exclude, and try again.  
4. Try to generate from other method, other JAVA file.

**Comment by randy** [comment]
> According to your description, there are several possibilities:
> 
> 1. If you generate from Groovy code, most of time you will get one initially call. It is the limit of Groovy(No UAST support in method body).

Well, I guess that answers that. You should make that more clear in the plugin description because it's effectively useless for Groovy source. Better still, don't list Groovy as supported because it really isn't since "No UAST support in method body."
