### ISSUE TITLE
匿名内部类在流程图里面只是显示() ->

### ISSUE THREAD

**Issue by 834116404** [Vanco/SequencePlugin#165]
代码里面显示的是:

![image](https://github.com/Vanco/SequencePlugin/assets/36099756/c24070cd-36fd-4222-bc0b-fb920e8797f4)

在流程图里面显示的是:
![image](https://github.com/Vanco/SequencePlugin/assets/36099756/9454abcf-20a2-46e1-ade8-e9b7798b1082)

**Comment by 834116404** [comment]
在这种匿名内部类里面的代码不显示.. 这个是不是个问题.

**Comment by Vanco** [comment]
This is Lambda expression presentation. you can opt-out `Show lambda call` in `Settings>Tools>Sequence Diagram`.

**Comment by 834116404** [comment]
> Owner
我看了下不管用.

![image](https://github.com/Vanco/SequencePlugin/assets/36099756/3a06c513-5963-4fcc-818b-50d69e25ed60)

下面还是出现 ()->

![image](https://github.com/Vanco/SequencePlugin/assets/36099756/90ae1f8e-eadb-4e01-95b9-cb23b6662505)

**Comment by 834116404** [comment]
> This is Lambda expression presentation. you can opt-out `Show lambda call` in `Settings>Tools>Sequence Diagram`.
好了, 可以了..谢谢了.
