### ISSUE TITLE
[Feature request] parameter types in diagram

### ISSUE THREAD

**Issue by pixar02** [Vanco/SequencePlugin#168]
**Is your feature request related to a problem? Please describe.**
Sequence Diagrams don't show types (parameters and return type)

**Describe the solution you'd like**
An option that enables parameters in the sequence diagram.
ex. : 
`getName()` -> `getName() : String`
`setName()` -> `getName(name : String)` or `getName(String)`  (with "detailed option" enabled, it includes the parameters name)

**Comment by Vanco** [comment]
You can leave the `Show simple call name` option unselected in `Settings > Tools > SequenceDiagram`
