### ISSUE TITLE
why i see the context menu grayed out? can i use it with node application?

### ISSUE THREAD

**Issue by SkateFreak** [Vanco/SequencePlugin#17]
sorry if i got it wrong but maybe it's only for java

<img width="244" alt="screen shot 2017-02-27 at 10 14 36" src="https://cloud.githubusercontent.com/assets/2161649/23353541/aa6bed64-fcd5-11e6-896c-79ae16cce5a3.png">

**Comment by jayeshgarg** [comment]
This option is enabled if you right click when your cursor is present inside a method in Java class. Outside the class it may not work. This is so as it takes that method as the starting point and starts building the flow. Hope this helps.

**Comment by Vanco** [comment]
Yes it's only for java.   And as @jayeshgarg post, it enabled inside the method of Java class.
