### ISSUE TITLE
Licence is not working

### ISSUE THREAD

**Issue by DineshGuptaa** [Vanco/SequencePlugin#172]
**Describe the bug**
I purchased licence today for 1 month but I am ubable to export as PNG or JPG file or even PlantUML

**To Reproduce**
1. Go to 'right click o the method and generate SD'
2. Click on 'the export as PNG'
3. See error

**Expected behavior**
File save dialog box should open for save but I am seeing to activate dialog even product is register with me.

**Screenshots**
![image](https://github.com/Vanco/SequencePlugin/assets/23373711/22b69219-2c35-40e3-b9fc-f931a2b0293c)

![image](https://github.com/Vanco/SequencePlugin/assets/23373711/a1e55ab6-9629-4240-9bc8-7cdd1f4bcf8c)

**Plugin & IDE info:**
 - Plugin Version [e.g. 3.0.8]
 - IDE Name & Version [e.g. IDEA Comunity 2023.3.3]
 - Which language (e.g: Java, Kotlin, Scala, Groovy) you try to generate?

**Additional context**
Please provide me solution, it very urgent that's why I purchased it.
- code fragment
```java

```

**Comment by Vanco** [comment]
Please try to restart idea.
