### ISSUE TITLE
Export the diagram as Mermaid format file error

### ISSUE THREAD

**Issue by i-rtfsc** [Vanco/SequencePlugin#174]
**Describe the bug**
Export the diagram as Mermaid format file error

**To Reproduce**
1. Export the diagram as PlantUML ---> OK
2. Export the diagram as Mermaid ---> Failed, can't found the output file

**Plugin & IDE info:**
 - Plugin Version 3.0.9
 - IDEA Comunity 2024.1
 - Java

**Comment by Vanco** [comment]
The exported mermaid file will have `.mmd` extention. I tried, its work.   

Do you get any err infomation?

**Comment by i-rtfsc** [comment]
I don't know what the reason for the failure is, and I can't find the exported file. It seems like the failure resulted in no file being generated.
Where can I see the error message you mentioned?

**Comment by i-rtfsc** [comment]
btw, the old version can be exported mermaid file, but I have forgotten which version it is.

**Comment by Vanco** [comment]
I tried latest version with IC 2024.1 on MacOS. There is worked.     Try to choose a new empty directory to save the exported file.

**Comment by i-rtfsc** [comment]
I cleared all the configurations and cache of idea, and reinstalling the plugin, it can be worked.
