### ISSUE TITLE
Export image but image can't open

### ISSUE THREAD

**Issue by ekkachaij** [Vanco/SequencePlugin#175]
Describe the bug [PAID]
When exporting an image, regardless of the file type, two files are generated: image and temp. However, neither file can be opened.

To Reproduce

Go to 'export'
Click on 'Export Image'
Scroll down to 'Save'
See error - both files (image and temp) cannot be opened
Expected behavior
The expected behavior is that the image file should be viewable and there should not be an unusable temp file.

Screenshots
<img width="484" alt="image" src="https://github.com/Vanco/SequencePlugin/assets/151826356/ca39627a-f61b-437d-999f-bf6a4af62a70">

Plugin & IDE info:
OS: Windows 11
Plugin Version: 3.0.9
IDE Name & Version: IntelliJ Community Edition 2024.1.2
Which language: Java

**Comment by Vanco** [comment]
Please choose SVG file format when the diagram is really big.  

If you choose JPG, PNG, TIF file format, the export process will do transcode from SVG --> JPG, PNG, TIF. 

the apache batik trancoder might fail when the diagram is very big.

`*.temp` file is acturely a SVG format file.
