### ISSUE TITLE
The 'Expand Implementation' feature has a bug.

### ISSUE THREAD

**Issue by colorfulSunday** [Vanco/SequencePlugin#176]
**Describe the bug**
The 'Expand Implementation' feature has a bug.
My code structure is like:
![image1](https://github.com/Vanco/SequencePlugin/assets/21980777/294b9722-0b8c-421f-8f53-e55b44677dcf)

**To Reproduce**
Steps to reproduce the behavior :
![image2](https://github.com/Vanco/SequencePlugin/assets/21980777/6f531499-1ddf-44fb-bc61-b2af87f3684f)
See error：
![image3](https://github.com/Vanco/SequencePlugin/assets/21980777/b47d680b-830a-4c28-b3e0-74509b9b6d15)

**Expected behavior**
![image4](https://github.com/Vanco/SequencePlugin/assets/21980777/d658fc47-d32f-4940-95f4-be959f5f7790)

**Plugin & IDE info:**
 - Plugin Version : 3.0.10
 - IDE Name & Version : IntelliJ IDEA 2024.1.3 (Ultimate Edition)
 - For Java

**Comment by colorfulSunday** [comment]
It appears to be an interface where, within a sequence diagram, only one global implementation can be selected

**Comment by Vanco** [comment]
The interface `ClusterMessageSender` only have two implements `JGroupMessageSender` and `ClusterMessageSender4Log` according you picture 1.   So, when you `choose this implementation in picture 2`, you have chosen `JGroupMessageSender`, which will replace the `ClusterMessageSender4Log` with `JGroupMessageSender` and showing in the diagram as picture 3.

**Comment by colorfulSunday** [comment]
![image](https://github.com/user-attachments/assets/46cb6262-9069-46e7-8b94-4269363a167c)

I set the 'expand' twice on the 'bar' of 'ClusterMessageSender'. Initially, I chose 'ClusterMessageSender4Log' (which internally calls methods of 'JGroupMessageSender'). Then, for the second time, I selected 'JGroupMessageSender'. After this second selection, the initial setting of 'ClusterMessageSender4Log' was lost.

**Comment by Vanco** [comment]
Please check on version 3.0.11

**Comment by colorfulSunday** [comment]
![时序图插件Expend功能失效](https://github.com/user-attachments/assets/92b0a8d2-16a2-483c-b606-5e757f7d3fdc)
I have upgraded to version 3.0.11, but the 'Expand' feature is not working.

**Comment by Vanco** [comment]
To verify the issue, temporarily disable "Smart Interface" and try "Expend...", see what happens?

**Comment by colorfulSunday** [comment]
![image](https://github.com/user-attachments/assets/839f8b00-5f7b-4086-bc44-03d96693c5af)
As you suggested, I disabled the 'Smart Interface' feature, but the 'Expand' function is still not working.
![时序图插件Expend功能失效2](https://github.com/user-attachments/assets/760c5f64-aa75-4d5f-a13b-dfe375eef2cc)

**Comment by Vanco** [comment]
Thank you for the verification. The problem will be fixed soon in version 3.0.12.
