### ISSUE TITLE
Suggestion: Follow local interfaces

### ISSUE THREAD

**Issue by gorefest** [Vanco/SequencePlugin#178]
**Is your feature request related to a problem? Please describe.**
I am making use of the tool reverse engineering business processes in a legacy EJB software. My sequence diagrams halt on local interfaces.

**Describe the solution you'd like**
Follow the implementation, if

1. there is a local interface or an interface in general with only one implementation
2. there is a local interface or an interface in general with multiple implementations, because it is inherited, then follow the implementation of the local interface if there is only one implementation
3. mark this step in a specific colour or highlight it for a better understanding

**Describe alternatives you've considered**
sorry, no alternatives

**Additional context**
I created two plantuml's to emphasize the situation

Situation A: variable is of type of the interface, implementation is injected. Method is implemented in the implementation class.

![image](https://github.com/user-attachments/assets/bcc0b46d-c316-4f2f-9b36-003c0e7e8fcb)

Situation B: interface brings is a inherited method implemented by MyEjbService, variable is of type MyLocalInterface

![image](https://github.com/user-attachments/assets/4e71c020-09d1-4fc7-aa28-c6c5feb26d4b)

It would be absolutely great if this could be added to the plugin's capabilities, since it makes the entire process visible.

**Comment by Vanco** [comment]
Which plugin version do you use?

Hints of existing features:

1. Enable the `Smart Interface` option.  this will try to find implementation.
2. Use `Expend...` action menu to choose one implementation manually. When there is multi implementations.
3. The interface --> implementation already drawed as a dash line, which is diffrent from other call line.

If the combination of the above three points does not meet your needs, please let me know. 

It would be more helpful if you could also provide some pseudocode to describe your requirements scenario.

**Comment by gorefest** [comment]
Hello!

I am using latest&greatest according to my IDEA.

This are my settings 

![image](https://github.com/user-attachments/assets/72c9fe6c-da1b-4a9d-8240-c6b74480dd4c)

I have a ClientSessionBean injecting a Facade using the local interface with @EJB annotation. Here the generator stops:

![image](https://github.com/user-attachments/assets/02f7cdac-a7e5-4d1a-82c2-03f4f167e790)

The automatic detection fails, but choosing the "Expend" (typo?) menu item does the trick - so thanks for your hint!

I can add all implementations by expanding the lines.

Best Regards and keep up that great work :-)
