### ISSUE TITLE
Export PNG

### ISSUE THREAD

**Issue by Hyun-June-Choi** [Vanco/SequencePlugin#19]
For png export functionality, there is often a low memory problem.
Increasing IDE memory does not solve the problem.
Can you optimize memory(for PNG export) or add another format?
I think adding jpg is a simple solution.

**Comment by Vanco** [comment]
I test it with IDEA 2017.1.1 on macOS Sierra. No issue found.   which IDEA are you use?

**Comment by Hyun-June-Choi** [comment]
The environment that I use is Android Studio on macOS Sierra.
and that's not always the case, unless there's a lot of "call depth" option.
come to think of it, I think the memory problem is the same for jpeg.
It is also helpful to use only in IDE.
Thank you for your reply.

**Comment by Vanco** [comment]
You can add more memory to idea.vmoptions file, e.g.
-Xmx1750m
