### ISSUE TITLE
Export PNG exports cropped method names

### ISSUE THREAD

**Issue by jayeshgarg** [Vanco/SequencePlugin#20]
![sd](https://cloud.githubusercontent.com/assets/25030263/26194736/fd147884-3bd6-11e7-9a85-f9ee762a8285.png)
As per the image, the left side is a screenshot taken of the Intellij and right side is the part of PNG generated using export feature.

As we can see that in screenshot the method names are complete and in right they re cropped.

*Please note that there was only one class in my diagram and some of the method names are long.

Request you to please fix this.

**Comment by Vanco** [comment]
fixed in version 1.2.5

**Comment by jayeshgarg** [comment]
Thank you so much. :)
