### ISSUE TITLE
[Feature Request]  Kotlin support

### ISSUE THREAD

**Issue by nicomazz** [Vanco/SequencePlugin#21]
Is there any plan to add kotlin support?

**Comment by miszmaniac** [comment]
Exactly, is it?:)

**Comment by adityakamble49** [comment]
Is there any update on this issue?
I am not able to generate diagram in Kotlin function

**Comment by Avinm** [comment]
For now, one could just use Tools -> Kotlin -> Show Byte Code -> Decompile to generate an equivalent java file and generate the diagram using it. 
That said, @Vanco if you could point me on how to go about extending this for kotlin I could give it a shot and raise a PR.

**Comment by ivasku** [comment]
> For now, one could just use Tools -> Kotlin -> Show Byte Code -> Decompile to generate an equivalent java file and generate the diagram using it. Fortunately you only need to decompile the starting file and not its dependencies.
> That said, @Vanco if you could point me on how to go about extending this for kotlin I could give it a shot and raise a PR.

I have tried it like that, it does not work. Maybe can you explain in more detail how are you using this tool ?

**Comment by ivasku** [comment]
Kotlin support please

**Comment by jiewenpang** [comment]
hope support scala as well

**Comment by Ayfri** [comment]
When ? :)

**Comment by Vanco** [comment]
Please try v3.0.0-alpha.1
