### ISSUE TITLE
PNG export

### ISSUE THREAD

**Issue by matiwei** [Vanco/SequencePlugin#22]
I think, that exporting from IntelliJ with Dracula theme doesn't work as it should. It changes background color to white (or something light), and doesn't change font color or set it transparent(?).

Sequence plugin 1.2.5

IntelliJ IDEA 2017.2.5
Build #IC-172.4343.14, built on September 26, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by Vanco** [comment]
fixed in v1.2.6

**Comment by username123231** [comment]
This has happened with me. 1.2.6, 1.2.7, and 1.3.0

IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 11.0.2+9-b159.60 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-327.36.3.el7.x86_64

![test](https://user-images.githubusercontent.com/9409256/61749228-3cd44f00-ad70-11e9-8996-10dfb437d891.png)
