### ISSUE TITLE
Sequence Diagram option shows disabled

### ISSUE THREAD

**Issue by nimitbhargava** [Vanco/SequencePlugin#25]
Followed the explanation from [here](https://github.com/Vanco/SequencePlugin/wiki#how-to-use)

![image](https://user-images.githubusercontent.com/8358694/33115080-9500ec08-cf85-11e7-9b59-e10464b768c4.png)

The Sequence Diagram option is showing disabled.
[Expected] Sequence Diagram should be enabled when open from inside the class definition
I am just trying out this plug in on a php project in Intellij IDEA 17.2
Using [this](https://github.com/noetix/Simple-ORM) project to test the plug in.

**Comment by Vanco** [comment]
The Sequence Diagram is designed for JAVA code only. It will enable when you place the input cursor on java method name or inside  java method.

**Comment by nimitbhargava** [comment]
Appreciate the response. Thanks for clarification!

**Comment by Vishnu05** [comment]
I'm facing this issue @Vanco I'm trying to use this only for JAVA projects. Still, the option seems to be disabled. 
![image](https://user-images.githubusercontent.com/32086222/107498108-5db1fe80-6bb9-11eb-87de-26136d9a63c3.png)

**Comment by Vanco** [comment]
1) Open one JAVA file
2) Place the caret at the METHOD name

The menu should enabled.

**Comment by Vishnu05** [comment]
> 1. Open one JAVA file
> 2. Place the caret at the METHOD name
> 
> The menu should enabled.

![image](https://user-images.githubusercontent.com/32086222/107953126-b0782580-6fc0-11eb-98bb-4f0389f79d36.png)

**Comment by icecreamwala12** [comment]
Facing the same issue.
Also what do you mean by add caret in method name

**Comment by Vanco** [comment]
Place your cursor/caret  at the METHOD name.
or right click the method show context menu.

**Comment by Vishnu05** [comment]
@Vanco Thanks man it works, it is working when I place the cursor at the methods.
One thing to ask apart from the method does this extension create a whole structure of the Java project completely?

**Comment by Vanco** [comment]
> @Vanco Thanks man it works, it is working when I place the cursor at the methods.
> One thing to ask apart from the method does this extension create a whole structure of the Java project completely?

Not yet. Just make use of the power of IntelliJ's Power.
