### ISSUE TITLE
[Feature Request] Add return type to diagram

### ISSUE THREAD

**Issue by haningyu** [Vanco/SequencePlugin#36]
hi! can u add method's return type to a diagram?
I think I used this plugin well and made it well. And if this feature is added I will really love this plugin.

**Comment by haninkyu** [comment]
![2019-02-11 11 41 46](https://user-images.githubusercontent.com/8578213/52544120-0de5a480-2df2-11e9-88b3-5616094b5bba.png)
i want to like this. this image's method return void, so it has only 'return'. if method's return type is 'MyClass', it appears 'return MyClass'.

**Comment by Vanco** [comment]
You Can opt-out `Show simple call name` in Preferences.
<img width="400" alt="settings" src="https://user-images.githubusercontent.com/11991700/52638706-81300900-2f0d-11e9-9108-1baa8f235139.png">
The method should include return type. e.g. 
<img width="418" alt="full_method" src="https://user-images.githubusercontent.com/11991700/52641155-2e595000-2f13-11e9-907c-880065329c81.png">
