### ISSUE TITLE
help

### ISSUE THREAD

**Issue by leslie-forever** [Vanco/SequencePlugin#54]
I have installed this plun-in in IDEA. But the icon is dark, when I clicked the mouse at right. I can't use it.

**Comment by Vanco** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        First, Open JAVA file.
        Second, place the cursor in the METHOD, and right click the mouse....The icon should light for you.    Have fun. 
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                fanhuagang
                            
                    
                        
                            
                                    fanhuagang@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 5/20/2020 00:35，leslie-forever<notifications@github.com> wrote： 



I have installed this plun-in in IDEA. But the icon is dark, when I clicked the mouse at right. I can't use it.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by leslie-forever** [comment]
![image](https://user-images.githubusercontent.com/38000488/82395608-73592400-9a7e-11ea-9e5c-4aa13dd5cf90.png)
I have done what you said, but the icon is still unselectable...

**Comment by twalmsley** [comment]
For me the icon is only selectable when the cursor is on or immediately next to a method name. Clicking in a method leaves the icon greyed out. Its fine once you get used to it.

**Comment by Vanco** [comment]
http://vanco.github.io/SequencePlugin/ 
Please check the quick document.
