### ISSUE TITLE
Popup menu not showing on linux

### ISSUE THREAD

**Issue by AyrtonRicardo** [Vanco/SequencePlugin#6]
I'm using Ubuntu 14.04 and PhpStorm 2016.1 (145.258) and the menu doesn't show for me, but i have a question about where it's shown: "It's shown similar to add symfony service or generate phpdoc?"

error on console:
> [ 332771]   WARN - napi.components.ServiceManager - org.editorconfig.plugincomponents.SettingsProviderComponent requested as a service, but it is a component - convert it to a service or change call to ApplicationManager.getApplication().getComponent()

i think who it was fixed on #2 but didn't work for me.

**Comment by Vanco** [comment]
The SequenceDiagram ONLY support generate sequence diagram from java code. If you try to generate from php code, it not supported, the ' SequenceDiagram ...' menu will disabled.
The #2 fixed the popup menu, witch is the menu when click the sequence diagram, 'go to source\ remove' will be the menu list.

**Comment by AyrtonRicardo** [comment]
Oh, ok! Thanks man!
