### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by LovesAsuna** [Vanco/SequencePlugin#62]
I can't change the color of text

**Comment by Vanco** [comment]
Only shape color support customize in settings.

**Comment by LovesAsuna** [comment]
What does it mean

**Comment by LovesAsuna** [comment]
![K_IYF7E~}@P~S29U$XC KN3](https://user-images.githubusercontent.com/32810896/104981109-f59d4c00-5a42-11eb-8abb-31d7142c14d3.png)
The color of this font makes me hard to see what words are written

**Comment by LovesAsuna** [comment]
Then I saw that a few years ago, the Kotlin would be supported, but it has not been released yet.

**Comment by Vanco** [comment]
> ![K_IYF7E~}@P~S29U$XC KN3](https://user-images.githubusercontent.com/32810896/104981109-f59d4c00-5a42-11eb-8abb-31d7142c14d3.png)
> The color of this font makes me hard to see what words are written

1. please try to use default theme (light or dark) see what happened.
2. You can custom shape colors at Tools>Sequence Diagram  Settings.
![image](https://user-images.githubusercontent.com/11991700/104981932-89234c80-5a44-11eb-9763-38e49a8dd61d.png)

**Comment by LovesAsuna** [comment]
Why can't it be used with material theme?

**Comment by Vanco** [comment]
Sorry, unsupported 3rd theme.

**Comment by LovesAsuna** [comment]
and how soon will it support kotlin?

**Comment by Vanco** [comment]
It will take a while, it's lot of work to do.
