### ISSUE TITLE
[Feature Request]增加筛选jar包功能

### ISSUE THREAD

**Issue by cyberqinjh** [Vanco/SequencePlugin#66]
目前可选择只展示同一project中的类的调用，
如果勾选掉这个选项，则会展示所有依赖jar中的类的调用。
希望能够提供针对jar的过滤功能
比如不需要展示java.util.* 和 slf4j、guaua等开源jar的调用，只展示同公司的jar的调用

**Comment by Vanco** [comment]
类似java.util.*可以在Settings里面设置。已经有些功能。

**Comment by cyberqinjh** [comment]
> 类似java.util.*可以在Settings里面设置。已经有此功能。
感谢回复，确实有，找到了，多谢！
(要啥自行车)：如果除了exclude，还有include就更好了^o^
