### ISSUE TITLE
如何指定接口的实现类

### ISSUE THREAD

**Issue by huanglusong** [Vanco/SequencePlugin#67]
![image](https://user-images.githubusercontent.com/43409414/100844696-29360e00-34b7-11eb-8f47-96261d17840b.png)
请问如图所示的设置在什么位置？我使用的是最新版的插件2.0.3的，无论在系统设置还是插件面板中都没有找到相关的，所以请教一下

**Comment by Vanco** [comment]
1. uncheck the SmartInterface check box on generate popup diagram.
2. right click interface object in diagram, there will be a list of implementation class on the context menu.
3. choose one of it.
