### ISSUE TITLE
Cannot add SequenceDiagram to Android Studio 4.1.1

### ISSUE THREAD

**Issue by adarmawan117** [Vanco/SequencePlugin#69]
I found this error when adding to my **Android Studio 4.1.1** IDE.

![image](https://user-images.githubusercontent.com/46953807/102172884-55e12100-3ecc-11eb-9d3b-990808ddc3f2.png)

**Comment by Vanco** [comment]
SequenceDiagram 2.0.3 should work as the Android Studio 4.1.1 is based on Intellij IDEA 2020.1.
