### ISSUE TITLE
Add a working example to your home page for easy testing

### ISSUE THREAD

**Issue by clemens-tolboom** [Vanco/SequencePlugin#7]
I tried some java-ish version (I'm not using Java but needed an Sequence Diagram

```java

static class User {
    public static void create() {
        Service::create();

        Connector::submit();
    }
}

static class Service {
    static public void create() {
        Connector::upload();
    }

    static public void submitted() {
        ;
    }

}

static class Connector {
    public static void upload() {
        ;
    }

    public static void submit() {
        Service::submitted();
    }

}
```

which does not render what I expected.

![hello_java_-_untitled_-____ideaprojects_untitled__and_new_issue_ _vanco_sequenceplugin](https://cloud.githubusercontent.com/assets/371014/15653194/a7ab31e6-268b-11e6-9f6a-b86da5d04aa3.png)

**Comment by Vanco** [comment]
The SequenceDiagram plugin only support java code.  I don't think your example code is correct java code.

I played with similar code in java, 
```
public class A {

    static class User {
        public static void create() {
            Service.create();

            Connector.submit();
        }
    }

    static class Service {
        static public void create() {
            Connector.upload();
        }

        static public void submitted() {
            ;
        }

    }

    static class Connector {
        public static void upload() {
            ;
        }

        public static void submit() {
            Service.submitted();
        }

    }
}
```
and it diagram is like this:
![user-sequence-diagram](https://cloud.githubusercontent.com/assets/11991700/15850680/d25d4c94-2ccb-11e6-82e2-268dbf288478.png)

**Comment by clemens-tolboom** [comment]
Thanks for the java fix.I will retry using better java code. I work in IntelliJ now. TNX

Maybe you could add this example to your README.
