### ISSUE TITLE
bug：cannot save  configuration

### ISSUE THREAD

**Issue by Willing-Xyz** [Vanco/SequencePlugin#70]
![image](https://user-images.githubusercontent.com/12200332/103737812-ea532500-502d-11eb-9469-d61f06c6ec92.png)
**click “OK” is invalid.
Reopen the setting interface, the content just configured disappeared.**

---

IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on December 1, 2020
Licensed to IntelliJ IDEA Evaluator
Expiration date: January 14, 2021
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1974M
Cores: 6
Registry: compiler.automake.postpone.when.idle.less.than=1000, compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: AceJump, IdeaVIM, Key Promoter X, Statistic, google-java-format, GrepConsole, QAPlug, SequenceDiagram, com.alibaba.p3c.smartfox, MavenRunHelper, com.codota.csp.intellij, com.zhaow.restful.toolkit, zielu.gittoolbox, com.itangcent.idea.plugin.easy-yapi, JRebelPlugin, cn.wuzhizhan.plugin.mybatis, cn.yiiguxing.plugin.translate, izhangzhihao.rainbow.brackets

**Comment by Vanco** [comment]
use the following format:
java.lang.*
java.util.**
java.io.InputStream

each one line.

**Comment by Willing-Xyz** [comment]
> use the following format:
> java.lang.*
> java.util.**
> java.io.InputStream
> 
> each one line.

it's not work
