### ISSUE TITLE
有时点击调用节点无法跳到源代码

### ISSUE THREAD

**Issue by JackyChan** [Vanco/SequencePlugin#76]
在点击某个时序调用节点时，无法跳到源代码，这种情况时灵时不灵。

**Comment by zuilintan** [comment]
的确有遇到

**Comment by Vanco** [comment]
Improved in v2.10.   Please try the new version. If you still encounter the same problem, please let me know.

**Comment by JackyChan** [comment]
> Improved in v2.10. Please try the new version. If you still encounter the same problem, please let me know.

还是有问题，已经更新到v2.1.1，点击调用的节点标题，没有反应。而且是有些行有些不行，并不是所有都不行。也不能跳到lamda的调用代码。
