### ISSUE TITLE
SequencePlugin causes IntelliJ to become very slow

### ISSUE THREAD

**Issue by Breefield** [Vanco/SequencePlugin#77]
I installed SequencePlugin for a large kotlin project. Obviously I can't use the plugin, but this didn't change the fact that Intellij began hogging CPU resources.

<img width="990" alt="Screen Shot 2021-03-29 at 3 00 54 PM" src="https://user-images.githubusercontent.com/188498/112912737-1a4e1980-90ad-11eb-8624-755015a5c0e8.png">

I am not going to try and use the plugin anymore, but I wanted to let you know this issue exists. It may have to do with the fact that my project is very large.

**Comment by Vanco** [comment]
try lastest version.
