### ISSUE TITLE
Add support to the themes such as (one dark or Material)

### ISSUE THREAD

**Issue by LovesAsuna** [Vanco/SequencePlugin#80]
The plugin cannot display the text clearly when using the theme.
![X_0$9T7Y@}Z87A0HE9 {NFW](https://user-images.githubusercontent.com/32810896/114958004-b7be9100-9e94-11eb-81cb-e8806e901eaf.png)
The above part cannot be clearly seen

**Comment by Vanco** [comment]
default dark theme Darkula already supported.

**Comment by LovesAsuna** [comment]
But how soon will it support material theme?

**Comment by Vanco** [comment]
No plain to support 3rd theme.
