### ISSUE TITLE
建议可以流程图里面 新增alt/loop

### ISSUE THREAD

**Issue by ACodingJie** [Vanco/SequencePlugin#94]
1. 目前流程图略显单调只有箭头指向
2. 新增 alt/loop 功能实现, 层次结构更加明显

**Comment by ACodingJie** [comment]
1. At present, the flow chart is slightly monotonous and only the arrow points
2. The new alt/loop function is implemented, and the hierarchy is more obvious

**Comment by Vanco** [comment]
duplicated. #43
