### ISSUE TITLE
Text format support 

### ISSUE THREAD

**Issue by mpsoftesis** [Vanco/SequencePlugin#98]
hi there 
does SequencePlugin suport text format that are used at https://sequencediagram.org/

```
title This is a title

Alice->Bob:Click and drag to create a request or\ntype it in the source area to the left
Alice<--Bob:drag to move
note over Bob,Double click to edit text:Click the **?** icon for **instructions** and **examples**
Bob->(3)Double click to edit text:non-instantaneous message
```

![image](https://user-images.githubusercontent.com/68222126/126499374-2a0815a8-0a86-45bc-9534-4c4346e47fd3.png)

**Comment by Vanco** [comment]
What is your real want? Please make it more specific.

**Comment by mpsoftesis** [comment]
For example 

I have file  in my project **site|doc** folder -> login-sqeuence-diagramm.txt

it contains scenario (example from as https://sequencediagram.org/ )

```
title This is a title

Alice->Bob:Click and drag to create a request or\ntype it in the source area to the left
Alice<--Bob:drag to move
note over Bob,Double click to edit text:Click the **?** icon for **instructions** and **examples**
Bob->(3)Double click to edit text:non-instantaneous message
```

and is it possible to render this txt with SequencePlugin?

**Comment by Vanco** [comment]
No.   SequenceDiagram is designed for show sequence base on source code.   you can export generated diagram to PlantUML format (text) file, but import from txt file is not supported.
