### ISSUE TITLE
SequencePlugin shows puzzling warnings in the Problems tab

### ISSUE THREAD

**Issue by doublefx** [Vanco/SequencePlugin#99]
I guess there are unwanted warnings?

![image](https://user-images.githubusercontent.com/1222171/126751485-c8e7bebc-0926-47b4-8fb1-bcecd60d4dab.png)

**IntelliJ Details:**
IntelliJ IDEA 2021.2 RC (Ultimate Edition)
Build #IU-212.4746.52, built on July 20, 2021

Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 7 6.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: analyze.exceptions.on.the.fly=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.github.b3er.idea.plugins.arc.browser (0.23), com.github.chencn.yamlandprops (1.0.5), com.intellij.ideolog (203.0.27.0), com.jetbrains.ChooseRuntime (1.2), com.redhat.devtools.intellij.telemetry (0.0.1.9), com.robohorse.robopojogenerator (2.3.0), com.samdark.intellij-visual-studio-code-dark-plus (2.4), com.thvardhan.gradianto (4.4), de.netnexus.camelcaseplugin (3.0.8), net.seesharpsoft.intellij.plugins.csv (2.17.1), org.intellij.RegexpTester (1.0.8), git-extended-update-index (0.1.0), CheckStyle-IDEA (5.54.0), GrepConsole (11.10.211.6086.0), String Manipulation (8.15.203.000.3), de.docksnet.puml.syntaxchecker (0.2.0), org.apache.camel (0.5.5), org.sonarlint.idea (5.1.0.34721), org.dpytel.intellij.plugin.maventest (0.0.21), MavenRunHelper (4.15.212.000.0), com.intellij.lang.jsgraphql (2.9.1), SequenceDiagram (2.1.1), com.haulmont.jpab (4.2-212), zielu.gittoolbox (212.6.6), pro.bashsupport (2.0.3.212)
Kotlin: 212-1.5.10-release-IJ4746.52

**Comment by Vanco** [comment]
I try to add Intention Action for quick access SequenceDiagram.  
<img width="577" alt="Intention Action" src="https://user-images.githubusercontent.com/11991700/126847642-de185efa-926c-4a0b-a1f1-2df85ddef8ec.png">
It is the cause of these problems, Maybe a bit over-optimized. I'll rethink about it.
